modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/YukkuriC/HexFlow/issues"
license = "MIT"

[[mods]]
modId = "hexflow"
version = "${version}"
displayName = "HexFlow"
authors = "YukkuriC"
description = '''
Adds several new patterns for better control for spell evaluations.
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/MRC1BQpK/forge_updates.json"
displayURL = "https://modrinth.com/mod/hexflow"

[[mixins]]
config = "hexflow.mixins.json"

[[dependencies.hexflow]]
modId = "minecraft"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexflow]]
modId = "hexcasting"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
